---
- name: Deploy a web application
  hosts: target1
  tasks:
    - name: Install python dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - name: Install MySQL Db
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql-client
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: "yes"
    - name: Create Application Database
      mysql_db: name=employee_db state=present
    - name: Create Db user
      mysql_user:
        name: db_user
        password: Passw0rd
        state: present
        priv: '*.*:ALL'
    - name: Install Flask
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask-mysql
    - name: Download Source code
      get_url:
        url: https://raw.githubusercontent.com/mmumshad/simple-webapp/master/app.py
        dest: /opt/app.py
    - name: Start webserver
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
